apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-eqhgrilc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-eqhgrilc:967408fc326b65584bba6d5006797b516abd2ded@sha256:0fe3df886362af095f2049c5e1e2773ca1fd101556d884a01e47d445f65f6c2e
          name: container-image
